### ISSUE TITLE
物品无法正常显示，后台疯狂报错

### ISSUE THREAD

**Issue by jiajiaxd** [Fireflyest/CraftGUI#1]
当打开此界面时：
![image](https://user-images.githubusercontent.com/51043917/183616136-c1da8ea1-7116-464d-b935-1bcfd692f4ca.png)
所售物品无法正常显示，且后台一直不断报错
`
[17:34:16 ERROR]: Caught exception in thread Thread[Worker-Main-18,5,main]
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.3.39.jar%2324!/:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200) ~[authlib-3.3.39.jar%2324!/:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.3.39.jar%2324!/:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.m_182477_(SkullBlockEntity.java:141) ~[server-1.18.2-20220404.173914-srg.jar%23138!/:?]
        at net.minecraft.Util.m_137521_(Util.java:395) ~[server-1.18.2-20220404.173914-srg.jar%23138!/:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.m_182458_(SkullBlockEntity.java:136) ~[server-1.18.2-20220404.173914-srg.jar%23138!/:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
`
直到关闭该界面，报错才会停止

使用：Arclight 1.18.2
CraftGUI和GlobalMarket均为最新版

**Comment by Fireflyest** [comment]
看报错应该是头颅在显示皮肤的时候出现了问题，尝试删除玩家数据后重新加载

**Comment by Fireflyest** [comment]
看报错应该是头颅在显示皮肤的时候出现了问题，可能是存储玩家的uuid的时候出错了，尝试删除玩家数据(位于GlobalMarket 的 storage.db)后重新加载

> 当打开此界面时： ![image](https://user-images.githubusercontent.com/51043917/183616136-c1da8ea1-7116-464d-b935-1bcfd692f4ca.png) 所售物品无法正常显示，且后台一直不断报错 `[17:34:16 ERROR]: Caught exception in thread Thread[Worker-Main-18,5,main] java.lang.IllegalArgumentException: Name and ID cannot both be blank at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.3.39.jar%2324!/:?] at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200) ~[authlib-3.3.39.jar%2324!/:?] at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.3.39.jar%2324!/:?] at net.minecraft.world.level.block.entity.SkullBlockEntity.m_182477_(SkullBlockEntity.java:141) ~[server-1.18.2-20220404.173914-srg.jar%23138!/:?] at net.minecraft.Util.m_137521_(Util.java:395) ~[server-1.18.2-20220404.173914-srg.jar%23138!/:?] at net.minecraft.world.level.block.entity.SkullBlockEntity.m_182458_(SkullBlockEntity.java:136) ~[server-1.18.2-20220404.173914-srg.jar%23138!/:?] at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?] at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]` 直到关闭该界面，报错才会停止
> 
> 使用：Arclight 1.18.2 CraftGUI和GlobalMarket均为最新版

**Comment by jiajiaxd** [comment]
玩家数据？值的是插件的存储内容吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月9日(周二) 晚上7:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Fireflyest/CraftGUI] 物品无法正常显示，后台疯狂报错 (Issue #1)




 
看报错应该是头颅在显示皮肤的时候出现了问题，尝试删除玩家数据后重新加载

**Comment by Fireflyest** [comment]
GlobalMarket的数据，那个界面没办法根据玩家的uuid给头颅附上皮肤，可能是玩家的uuid数据记录出错了

**Comment by jiajiaxd** [comment]
我把globalmarket文件夹删除重启服务器之后依然有该bug



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月9日(周二) 晚上7:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Fireflyest/CraftGUI] 物品无法正常显示，后台疯狂报错 (Issue #1)




 
GlobalMarket的数据，那个界面没办法根据玩家的uuid给头颅附上皮肤，可能是玩家的uuid数据记录出错了

**Comment by Fireflyest** [comment]
把你ip地址给我，我进去看看

**Comment by jiajiaxd** [comment]
是本地测试的服务器😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月9日(周二) 晚上7:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Fireflyest/CraftGUI] 物品无法正常显示，后台疯狂报错 (Issue #1)




 
把你ip地址给我，我进去看看

**Comment by Fireflyest** [comment]
那把你完整日志发一下

**Comment by jiajiaxd** [comment]
[1.log](https://github.com/Fireflyest/CraftGUI/files/9290031/1.log)
后面就全是相同的了

**Comment by Fireflyest** [comment]
我发布了市场的新版本，你看看问题有没有解决

**Comment by jiajiaxd** [comment]
新版本依旧有该问题
![image](https://user-images.githubusercontent.com/51043917/183645514-61c912c9-145f-4704-b051-b4a7a7667bc2.png)

**Comment by jiajiaxd** [comment]
顺便再说个bug
就是从市场点自己上架的商品
有概率没法正确显示名字
显示为：
![image](https://user-images.githubusercontent.com/51043917/183647975-6bef82c0-5637-4594-ac61-96462ff467ea.png)

**Comment by Fireflyest** [comment]
这是同一个错误来的，不知道为啥你这个端它可能获取离线用户的方式不一样

**Comment by Fireflyest** [comment]
你把日志的latest.log文件发一下，我看下完整的日志，有可能从出售的时候就有错误了

**Comment by jiajiaxd** [comment]
出售的时候没有任何问题

**Comment by Fireflyest** [comment]
这个界面物品的展示顺序是商品、交易按钮、统计书，最后才是个人头颅。我看到你界面里面只有固定按钮，并没有异步加载的按钮。说明商品数据可能有问题。你可以发送你完整的运行记录，或者storage.db给我，我才能看出问题出在哪

**Comment by jiajiaxd** [comment]
[storage.zip](https://github.com/Fireflyest/CraftGUI/files/9291387/storage.zip)

**Comment by Fireflyest** [comment]
我看了数据没什么问题，在我的服务端上也正常显示。现在排除头颅问题的可能性，输入/mka 找到个人商店的按钮，使用其他材质的物品将其替换，然后重载服务器，看看别的按钮的情况下，有没有错误

**Comment by jiajiaxd** [comment]
个人商店的按钮还能替换？
（我刚关电脑，明天测试）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月9日(周二) 晚上10:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Fireflyest/CraftGUI] 物品无法正常显示，后台疯狂报错 (Issue #1)




 
我看了数据没什么问题，在我的服务端上也正常显示。现在排除头颅问题的可能性，输入/mka 找到个人商店的按钮，使用其他材质的物品将其替换，然后重载服务器，看看别的按钮的情况下，有没有错误

**Comment by Fireflyest** [comment]
按钮可以自定义的，把新按钮拖上去替换就行

**Comment by jiajiaxd** [comment]
我进入这个界面后一直闪 拖也拖不动
![1](https://user-images.githubusercontent.com/51043917/183793890-d8131fb8-48a1-40e7-8613-fd2c8fbf5a9e.gif)

**Comment by Fireflyest** [comment]
你的ProtocolLib插件是什么版本的

**Comment by jiajiaxd** [comment]
ProtocolLib v5.0.0-SNAPSHOT-b567

**Comment by Fireflyest** [comment]
这个版本是开发板，请使用稳定版

**Comment by jiajiaxd** [comment]
因为4.8.0版本的ProtocolLib对1.18.2的支持并不好（会导致玩家无法加入服务器），故更新到了最新的开发版ProtocolLib
在更新了最新版的ProtocolLib后，输入/mka会出现以下报错：
```
[10:47:29 ERROR]: Error receiving packet 20
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41619_()" because "p_130056_" is null
        at net.minecraft.network.FriendlyByteBuf.writeItemStack(FriendlyByteBuf.java:451) ~[server-1.18.2-20220404.173914-srg.jar%23138!/:?]
        at net.minecraft.network.FriendlyByteBuf.m_130055_(FriendlyByteBuf.java:442) ~[server-1.18.2-20220404.173914-srg.jar%23138!/:?]
        at net.minecraft.network.protocol.game.ClientboundContainerSetContentPacket.m_5779_(ClientboundContainerSetContentPacket.java:39) ~[server-1.18.2-20220404.173914-srg.jar%23138!/:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:45) [server-1.18.2-20220404.173914-srg.jar%23138!/:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) [server-1.18.2-20220404.173914-srg.jar%23138!/:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at me.arasple.mc.trchat.taboolib.module.nms.ChannelHandler.write(ChannelHandler.kt:19) [TrChat-2.0.0-PRE-10.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```
然后就会把玩家卡出服务器

**Comment by Fireflyest** [comment]
ProtocolLib 5.0.0版本发送异步包似乎有问题，昨天刚测试了1.19版本发现无法异步发送更新容器的包，导致界面一直在刷新

**Comment by jiajiaxd** [comment]
emmm那没有解决方案了吗？

**Comment by Fireflyest** [comment]
我在ProtocolLib插件发布了这个问题，看看作者怎么说吧，主要是5.0.0现在不是很稳定，问题挺多的。目前是没有什么解决办法，只能等作者更新了。

**Comment by Fireflyest** [comment]
我根据ProtocolLib作者给我的回复做了些修改，解决了一直重复刷新的问题 v1.0.10
